version: '3'

services:
  testsmtp:
    image: mailhog/mailhog
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    ports:
      - 8025:8025
  bauer-db:
    image: mariadb
    volumes:
      - bauer-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=bauer
      - MYSQL_DATABASE=bauer
      - MYSQL_USER=bauer
      - MYSQL_PASSWORD=bauer
  bauer-ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    depends_on:
      - bauer-drf
    volumes:
      - .:/app
    ports:
      - 8080:8080
  bauer-drf:
    image: bauer-drf
    depends_on:
      - bauer-db
    volumes:
      - .:/app
    links:
      - bauer-db
      - testsmtp
    ports:
      - 8099:80
    environment:
      - BAUER_IFX_APP_TOKEN=52b28b781722283740d228ce311a487227ec26a4
      - BAUER_USERNAME=bauer
      - BAUER_PASSWORD=bauer
      - BAUER_DATABASE=bauer
      - BAUER_HOSTNAME=bauer-db
      - BAUER_LOGLEVEL=DEBUG
      - BAUER_DEBUG=TRUE
      - BAUER_DJANGO_KEY=akjdkwifheilskeit8n99f0k2nvi02ld0
      - SMTP_SERVER=testsmtp
      - IFX_REMOTE_USER=veradmin

volumes:
  bauer-data:
